print('tetdtdtdtdtd')
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")

print("skfksmfkmskdsfksdmkfmksdmfmkf")



print("skfksmf11111111111111111111111111111111111111kmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")


print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")