print('tetdtdtdtdtd')
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")

print("skfksmfkmskdsfksdmkfmksdmfmkf")



print("skfksmf11111111111111111111111111111111111111kmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmsgvvbvbvkf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksdvbvbvbvbfdfdmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfdfdfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("dfdfdf")
print("skfksmfkmskf")
print("skfksmfkmskf")
print("skfksmfkmskf")